package com.spring.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.model.BaseModel;
import com.liferay.portal.model.CacheModel;
import com.liferay.portal.model.GroupedModel;
import com.liferay.portal.service.ServiceContext;

import com.liferay.portlet.expando.model.ExpandoBridge;

import java.io.Serializable;

import java.util.Date;

/**
 * The base model interface for the Employee service. Represents a row in the &quot;spring_Employee&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation {@link com.spring.model.impl.EmployeeModelImpl} exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link com.spring.model.impl.EmployeeImpl}.
 * </p>
 *
 * @author 556823
 * @see Employee
 * @see com.spring.model.impl.EmployeeImpl
 * @see com.spring.model.impl.EmployeeModelImpl
 * @generated
 */
public interface EmployeeModel extends BaseModel<Employee>, GroupedModel {
    /*
     * NOTE FOR DEVELOPERS:
     *
     * Never modify or reference this interface directly. All methods that expect a employee model instance should use the {@link Employee} interface instead.
     */

    /**
     * Returns the primary key of this employee.
     *
     * @return the primary key of this employee
     */
    public long getPrimaryKey();

    /**
     * Sets the primary key of this employee.
     *
     * @param primaryKey the primary key of this employee
     */
    public void setPrimaryKey(long primaryKey);

    /**
     * Returns the emp ID of this employee.
     *
     * @return the emp ID of this employee
     */
    public long getEmpId();

    /**
     * Sets the emp ID of this employee.
     *
     * @param empId the emp ID of this employee
     */
    public void setEmpId(long empId);

    /**
     * Returns the group ID of this employee.
     *
     * @return the group ID of this employee
     */
    @Override
    public long getGroupId();

    /**
     * Sets the group ID of this employee.
     *
     * @param groupId the group ID of this employee
     */
    @Override
    public void setGroupId(long groupId);

    /**
     * Returns the company ID of this employee.
     *
     * @return the company ID of this employee
     */
    @Override
    public long getCompanyId();

    /**
     * Sets the company ID of this employee.
     *
     * @param companyId the company ID of this employee
     */
    @Override
    public void setCompanyId(long companyId);

    /**
     * Returns the user ID of this employee.
     *
     * @return the user ID of this employee
     */
    @Override
    public long getUserId();

    /**
     * Sets the user ID of this employee.
     *
     * @param userId the user ID of this employee
     */
    @Override
    public void setUserId(long userId);

    /**
     * Returns the user uuid of this employee.
     *
     * @return the user uuid of this employee
     * @throws SystemException if a system exception occurred
     */
    @Override
    public String getUserUuid() throws SystemException;

    /**
     * Sets the user uuid of this employee.
     *
     * @param userUuid the user uuid of this employee
     */
    @Override
    public void setUserUuid(String userUuid);

    /**
     * Returns the user name of this employee.
     *
     * @return the user name of this employee
     */
    @AutoEscape
    @Override
    public String getUserName();

    /**
     * Sets the user name of this employee.
     *
     * @param userName the user name of this employee
     */
    @Override
    public void setUserName(String userName);

    /**
     * Returns the create date of this employee.
     *
     * @return the create date of this employee
     */
    @Override
    public Date getCreateDate();

    /**
     * Sets the create date of this employee.
     *
     * @param createDate the create date of this employee
     */
    @Override
    public void setCreateDate(Date createDate);

    /**
     * Returns the modified date of this employee.
     *
     * @return the modified date of this employee
     */
    @Override
    public Date getModifiedDate();

    /**
     * Sets the modified date of this employee.
     *
     * @param modifiedDate the modified date of this employee
     */
    @Override
    public void setModifiedDate(Date modifiedDate);

    /**
     * Returns the emp name of this employee.
     *
     * @return the emp name of this employee
     */
    @AutoEscape
    public String getEmpName();

    /**
     * Sets the emp name of this employee.
     *
     * @param empName the emp name of this employee
     */
    public void setEmpName(String empName);

    /**
     * Returns the grade of this employee.
     *
     * @return the grade of this employee
     */
    @AutoEscape
    public String getGrade();

    /**
     * Sets the grade of this employee.
     *
     * @param grade the grade of this employee
     */
    public void setGrade(String grade);

    @Override
    public boolean isNew();

    @Override
    public void setNew(boolean n);

    @Override
    public boolean isCachedModel();

    @Override
    public void setCachedModel(boolean cachedModel);

    @Override
    public boolean isEscapedModel();

    @Override
    public Serializable getPrimaryKeyObj();

    @Override
    public void setPrimaryKeyObj(Serializable primaryKeyObj);

    @Override
    public ExpandoBridge getExpandoBridge();

    @Override
    public void setExpandoBridgeAttributes(BaseModel<?> baseModel);

    @Override
    public void setExpandoBridgeAttributes(ExpandoBridge expandoBridge);

    @Override
    public void setExpandoBridgeAttributes(ServiceContext serviceContext);

    @Override
    public Object clone();

    @Override
    public int compareTo(Employee employee);

    @Override
    public int hashCode();

    @Override
    public CacheModel<Employee> toCacheModel();

    @Override
    public Employee toEscapedModel();

    @Override
    public Employee toUnescapedModel();

    @Override
    public String toString();

    @Override
    public String toXmlString();
}
